language: python

sudo: required

python:
  - "2.7"

before_install:
    - sudo sh tools/libgit2.sh
    - pip install -r test-requirements.txt
    - pip install -r requirements.txt
    - pip install tox
    - pip install pygit2==0.25.0

install:
    - pip install -e .

script:
    - flake8
    - armada -h
    - nosetests -w armada/tests/unit --cover-package=armada --with-coverage --cover-tests

after_success:
     - codecov
